# -*- coding: utf-8 -*-
"""prototipo en python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jK92pFFT_eUNoTrBSo7HklAUKG9WEL-3
"""

!pip install paho-mqtt

import paho.mqtt.client as mqtt

"""PUBLICADOR"""

client = mqtt.Client()
client.connect("test.mosquitto.org", 1883, 60)
client.publish("ALSW/temp", "Chao")

"""SUBSCRIPTOR"""

def on_connect(client, userdata, flags, rc):
  print("SE HA CONECTADO mediante MQTT"+str(rc))
  client.subscribe("ALSW/#")

def on_message(client, userdata, msg):
  if msg.topic == "ALSW/temp":
    print(f"Temperatura es {str(msg.payload)}")
  print(msg.topic+" "+str(msg.payload))

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect("test.mosquitto.org", 1883, 60)
client.loop()